### ISSUE TITLE
Dockerise everything

### ISSUE THREAD

**Issue by NamanArora** [TheDevExperiment/server#5]
Local dev environments can vary alot so we want everything to run inside a container so that our server code becomes platform agnostic. This will also help us later on in deployment.

**Comment by sathvik-t** [comment]
Hey, I can take up this issue!

**Comment by keshav2010** [comment]
hey @sathvik-t you still working on it ? if so, you may assign this issue to yourself

**Comment by NamanArora** [comment]
In order to expedite db integration, I was able to pick this issue and execute it.
https://github.com/TheDevExperiment/server/pull/7

Ref: https://docs.docker.com/language/golang/build-images/
If there are any doubts/blockers lmk @sathvik-t I mostly copied code from up there^
